### ISSUE TITLE
非常感谢您的解答

### ISSUE THREAD

**Issue by dugzzuli** [Guanzhou-Ke/conan#4]
非常感谢您的解答
不过我没有理解到这个视图之间的对比，是通过那一句代码？怎么对比的？
ps通过第二个维度进行串联，shape应该表示为100X200
h1的shape为50*200.
“(h1 @ h1.t())” 这个计算得到的是对半的batch做正负样本，也就是说假设batch为100，那么取前50个和后50个进行对比，为什么这么做呢，不应该是一致性表示的100个样本和视角表示100个样本之间的对比吗？
有点不太理解，

**Comment by Guanzhou-Ke** [comment]
非常感谢您的关心，但是仍然想提醒一下您，仔细阅读一下代码。

我们以SimCLR module为例在`models.py`中的get_loss定义如下:
```
def get_loss(self, ch, hs):
        cp = self(ch)
        sub_loss = 0
        for h in hs:
            p = self(h)
            ps = torch.cat([cp, p], dim=-1)
            sub_loss += self.con_criterion(ps)
        return self.con_lambda * sub_loss
```

您应该可以清楚的看到，假设此时的ps为100x200,那么 50x200 cp为的融合空间的维度，而各个视图的projection维度也是50x200。我们让cp与各个视图的projection进行对齐，目的就是希望增大之间的互信息。

`(h1 @ h1.t())`是计算自相似度，请仔细查看SimCLR的损失，推荐您阅读一下Ting Chen的SimCLR原文。如果您已经非常熟悉的话请忽略。

非常感谢！
